<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign up</name>
   <tag></tag>
   <elementGuidId>bf79cf6a-3064-45fe-970d-5264075f8821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.signUp.ml-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home_login']/div/div/div[2]/div/div/div[2]/div/div[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4400832-72d6-4d16-b737-1e8fc584bf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/signup</value>
      <webElementGuid>1760e05f-9984-45f1-9dc6-4f618095797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signUp ml-1</value>
      <webElementGuid>a7d11645-0a33-4f53-be7a-1539df1614c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>bfd2594c-e509-4c1e-ad22-3b70003021ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_login&quot;)/div[@class=&quot;home_login_inner&quot;]/div[@class=&quot;home_login_inner_row&quot;]/div[@class=&quot;home_login_inner_right&quot;]/div[@class=&quot;login-wrapper&quot;]/div[1]/div[@class=&quot;login_col_div&quot;]/div[@class=&quot;card border-0 shadow-none&quot;]/div[@class=&quot;card-body p-0 bg-transparent&quot;]/p[@class=&quot;mt-4 text-sm text-center&quot;]/a[@class=&quot;signUp ml-1&quot;]</value>
      <webElementGuid>88a9f8ae-c971-43d1-ad2e-2c03f034a884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home_login']/div/div/div[2]/div/div/div[2]/div/div[2]/p/a</value>
      <webElementGuid>658c5d19-b088-41cd-8a02-097968424bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up')]</value>
      <webElementGuid>90b16048-09db-4d01-981a-8541205a9c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::a[1]</value>
      <webElementGuid>c91bfbd2-ca06-4b80-9c1e-5e7db4bb0b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::a[1]</value>
      <webElementGuid>60d17fd7-92c6-4657-ab60-c8e29d4699db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[2]/preceding::a[1]</value>
      <webElementGuid>776510e2-beac-4c7d-a1f6-ad05b1736a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caterpillar'])[1]/preceding::a[1]</value>
      <webElementGuid>40095c24-f3a7-40b7-9202-33a9f6bbd27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up']/parent::*</value>
      <webElementGuid>d45d185d-2f40-4257-8459-36cf895f7088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/signup')]</value>
      <webElementGuid>653a32f8-c2b2-4112-bbb4-6d82970e52fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>9fc4bc08-f9ac-43b6-83e6-b0a057f5985b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/signup' and (text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>2e408206-5694-4e8a-9e7d-291d8c72c0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
