<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-1 Issue created SuccessfullyClick here_4f8063</name>
   <tag></tag>
   <elementGuidId>dbf75b0a-a479-4cce-a80c-f74cc4ead05b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Toastify__toast-body > div:nth-of-type(2) > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a5456d5-7b63-48ae-8799-03b58c796b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-1 Issue created Successfully!!Click here to view the issue</value>
      <webElementGuid>3a65f16a-b797-44be-9cd5-fd6d4380b0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;Toastify__toast-body&quot;]/div[2]/div[1]</value>
      <webElementGuid>989323f2-8111-4b0f-9814-ab5ad7488281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div/div[2]/div</value>
      <webElementGuid>2ce28292-f1b2-4fe8-b1a5-d9f5d2b9fb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite'])[1]/following::div[7]</value>
      <webElementGuid>30a37d29-5373-48e2-a0de-c545def79c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::div[7]</value>
      <webElementGuid>9c7558bb-4703-469d-90bb-2d2d2b8e6315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Issue'])[1]/preceding::div[4]</value>
      <webElementGuid>4da3c6bc-170d-4d0f-9324-ad1daffa02df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>49a8f2ac-2a56-4746-89ed-3de417698ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>589003d2-7fdf-4067-a9c5-bb0c76f4d62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '-1 Issue created Successfully!!Click here to view the issue' or . = '-1 Issue created Successfully!!Click here to view the issue')]</value>
      <webElementGuid>3a2d8259-c22d-4bf3-a16f-65bca7d73f3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
