<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bug</name>
   <tag></tag>
   <elementGuidId>4c49e776-ad19-44c4-9996-fc0063b9aa7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[2]/div[5]/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>563df035-29bc-4afe-8bd4-024d83a322ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ImageNamePjt</value>
      <webElementGuid>48c2f3a4-e8d3-4fec-8d74-0137b7e46805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bug</value>
      <webElementGuid>77e543a0-9b10-4635-84b6-38e19f81dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;bodywrapper mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-div form-div-darkmode col-xl-6 col-md-6 col-sm-7 pt-3&quot;]/div[@class=&quot;row tag_formLabel&quot;]/div[@class=&quot;col-sm-8 col-xl-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;cards&quot;]/div[@class=&quot;ImageNamePjt&quot;]</value>
      <webElementGuid>462336c7-4a0d-483e-88bd-627976a2bf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[2]/div[5]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>5e1302cd-3cb4-4648-9a40-85087a7937a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scrum'])[1]/following::div[4]</value>
      <webElementGuid>30a288e7-ba69-4be1-be3d-0ed1ca1292b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[10]</value>
      <webElementGuid>115e1910-51bb-4594-88e3-34b5dff36b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::div[1]</value>
      <webElementGuid>147efa16-a8d0-409c-a386-cac61db67e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bug']/parent::*</value>
      <webElementGuid>4c42d747-cbdf-4d51-8786-152adfb044ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>52eecf83-5047-4ee2-a729-06dd8addc85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bug' or . = 'Bug')]</value>
      <webElementGuid>f1f63f23-0d92-4310-8763-8114f710e7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div[5]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>96f1a27b-25dd-4620-823d-9d94d64c460e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
