<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create new</name>
   <tag></tag>
   <elementGuidId>352cb014-67f4-41a1-93bc-91bdee0c7193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.taskContents</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd9f2dd4-23d4-4d41-b6ab-9ab87a2c4eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>taskContents</value>
      <webElementGuid>f5440ba1-e121-4092-b2c8-bac85df079f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new</value>
      <webElementGuid>906f0d97-441d-4195-ae67-7db9a89ebe89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;scrollDiv&quot;]/div[@class=&quot;scroll_div_flex&quot;]/div[@class=&quot;mt-3 mainTaskData mb-3&quot;]/div[2]/div[1]/div[@class=&quot;taskBlock&quot;]/div[@class=&quot;tasks&quot;]/div[@class=&quot;taskContents&quot;]</value>
      <webElementGuid>7990186f-d627-4017-b472-6205cad8f2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>812be585-a248-4300-84f9-c884c9622003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/following::div[9]</value>
      <webElementGuid>46f23472-fbe6-42ee-9130-c8e2f0fc292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN PROGRESS'])[2]/preceding::div[6]</value>
      <webElementGuid>713e22ac-a25c-4758-a6de-02cb672bb98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new']/parent::*</value>
      <webElementGuid>4b166d62-6341-4cde-91f7-aa4080914853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>6fbbbda7-81ef-4d02-ab4d-db8fbdb59df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Create new' or . = 'Create new')]</value>
      <webElementGuid>be47a300-fcbd-4550-bb06-5f5eddec4024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
