<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Scrum_img-fluid</name>
   <tag></tag>
   <elementGuidId>3d204a62-4d37-4b5e-9514-ab9358871330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>eedad258-0a69-424e-a8f2-b7157cd3ee52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/bug.c6e0790722ec6cb1e37338aab6fbb7c8.svg</value>
      <webElementGuid>cbd88a75-2131-4cb3-b7cd-d46326d9df6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ScrumImg</value>
      <webElementGuid>20f78e94-6fde-489f-8995-04dd30814dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>6b0cbc4e-e4af-499b-9986-e71ecfe64225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;bodywrapper mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-div form-div-darkmode col-xl-6 col-md-6 col-sm-7 pt-3&quot;]/div[@class=&quot;row tag_formLabel&quot;]/div[@class=&quot;col-sm-8 col-xl-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;cards&quot;]/div[@class=&quot;ImagePjt&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>27429086-1bd2-4b26-a96d-28511853ecea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[2]/div[5]/div/div/div[2]/div/div/img</value>
      <webElementGuid>a956480f-8381-4868-be80-76078e0a2cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='ScrumImg'])[2]</value>
      <webElementGuid>5d5b8036-5023-4cdf-b768-a5e8251d284e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>59170d28-4276-48f3-98f3-72f08e4da11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/bug.c6e0790722ec6cb1e37338aab6fbb7c8.svg' and @alt = 'ScrumImg']</value>
      <webElementGuid>129a15fb-2cc4-41cc-bac8-667f90cf28ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
