<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__img-fluid</name>
   <tag></tag>
   <elementGuidId>e152f589-b487-4c95-857a-48e5e3bd4867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ImagePjt > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ImageNamePjt' and text()='Scrum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>761c0956-40e4-4908-a722-032555a0f60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/scrum.0dd9258655cd7c968028820a24b7e5c6.svg</value>
      <webElementGuid>2b60c683-298d-4eef-b615-fd4bbf6de17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ScrumImg</value>
      <webElementGuid>eacf62f9-d895-4170-842a-56e5e26b015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>18c069a0-bb9d-4e57-9696-93514c546820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;bodywrapper mt-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-div form-div-darkmode col-xl-6 col-md-6 col-sm-7 pt-3&quot;]/div[@class=&quot;row tag_formLabel&quot;]/div[@class=&quot;col-sm-8 col-xl-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;cards&quot;]/div[@class=&quot;ImagePjt&quot;]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>402d60d8-a6ac-4f47-9208-76352d309ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div[5]/div/div/div/div/div/img</value>
      <webElementGuid>dc5292ef-f3e7-4b27-94e3-b091a9251adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ScrumImg']</value>
      <webElementGuid>ab54ffa5-29b8-459f-b588-d218132b97b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/img</value>
      <webElementGuid>cd6c22dc-b85e-4c04-a8e0-b01e2fdc70c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/scrum.0dd9258655cd7c968028820a24b7e5c6.svg' and @alt = 'ScrumImg']</value>
      <webElementGuid>a9c6c211-1c49-475e-af00-39c10753063b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
