<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ipAddress</name>
   <tag></tag>
   <elementGuidId>a350eee8-0a1f-495a-8b94-f48e0375a9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ipAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ipAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dfa5174-1db9-464b-baee-9a8ee9ab6e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Description</value>
      <webElementGuid>712c091c-fea4-44c8-b67e-1de772fe20dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66cc4aef-9247-41ce-88d1-275c378bc988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6224e518-ee66-4934-acf1-5d38c0df59a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ipAddress</value>
      <webElementGuid>bc98147e-cd95-490b-8d50-670417e9899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ipAddress&quot;)</value>
      <webElementGuid>4cf0b145-3661-4c62-9a41-eb92e82c4a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ipAddress']</value>
      <webElementGuid>a2119892-d16e-4455-985d-6c452297ea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div[4]/div/input</value>
      <webElementGuid>649b3d9d-d0f3-493a-afb2-a24a5ce16a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>777468b5-33cb-4dff-aed1-f970ba67962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Add Description' and @type = 'text' and @id = 'ipAddress']</value>
      <webElementGuid>1e90512a-2082-47b2-92a5-500d321000f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
