<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NewSection_editHeading-3</name>
   <tag></tag>
   <elementGuidId>4b4781af-9fc0-4871-a85b-bdf35f468d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editHeading-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#editHeading-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4592a88-e9e4-4008-8194-df205d32bc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editHeading-3</value>
      <webElementGuid>300b693a-f7ad-4a8b-b492-2b591bbeaa9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24931e9a-57b2-46e7-80b3-f531ccf9f69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editHeading-3&quot;)</value>
      <webElementGuid>3f5f9a04-e976-4aaa-a699-8b0bba1b39b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editHeading-3']</value>
      <webElementGuid>514075df-8c2f-45d1-bdfb-f5ac8afd4675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[4]/div/div[4]/div/input</value>
      <webElementGuid>5472fe0d-8aa9-48d8-b2e6-ce3e7e924745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/input</value>
      <webElementGuid>f1347320-ec0d-4a07-8e77-cd4d5460cc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'editHeading-3']</value>
      <webElementGuid>eb7bdf8a-4868-4ca6-bdd6-20ded5cfa07f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
