<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ANAnjanaNair</name>
   <tag></tag>
   <elementGuidId>05499675-c42e-4717-ba33-88824e0c808e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-items</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='yourTeam']/div/ul/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c70c41e8-82f7-4eb1-ae12-fb14564924a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-items</value>
      <webElementGuid>b84be435-c8fc-4b70-a3df-8d722b42c20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AN Anjana Nair</value>
      <webElementGuid>0ddfc2b0-c521-4b68-80e7-f8995460b655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yourTeam&quot;)/div[@class=&quot;dropdown_div&quot;]/ul[@class=&quot;nav flex-column&quot;]/ul[@class=&quot;nav flex-column&quot;]/li[@class=&quot;nav-items&quot;]</value>
      <webElementGuid>5fb013fc-7595-4195-bd5e-e5c9ddb4e144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yourTeam']/div/ul/ul/li</value>
      <webElementGuid>9899f78d-081a-4b59-af6a-1882ef0e333c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Team'])[2]/following::li[1]</value>
      <webElementGuid>cd06e7c5-96df-43f0-a41c-01f42cdb7e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Team'])[1]/following::li[1]</value>
      <webElementGuid>8207a826-647f-4380-b722-112044ed7c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anjana']/parent::*</value>
      <webElementGuid>8bcc2ffe-c6ea-4277-b2a0-881ca00c236a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>5aa541f0-3428-47b8-9e7c-ac6a922d8cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'AN Anjana Nair' or . = 'AN Anjana Nair')]</value>
      <webElementGuid>8b084488-bbe4-49b2-a9e5-1096374adf9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
