<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create new</name>
   <tag></tag>
   <elementGuidId>28268cb7-729e-4e6b-9adc-0183195283f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div/h3/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.issue_list_summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7e81d80-737d-458b-9be5-b8628847844a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>issue_list_summary</value>
      <webElementGuid>b77dfc41-dbbe-43c3-b205-b1f1e386f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new</value>
      <webElementGuid>588705e4-3e45-4be2-af0f-725474913d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 col-md-12&quot;]/div[@class=&quot;main-accordion-wrapper&quot;]/div[1]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-item&quot;]/h3[@class=&quot;accordion-title&quot;]/div[@class=&quot;backlog_test&quot;]/div[@class=&quot;col-md-9 issueNames&quot;]/span[@class=&quot;issue_list_summary&quot;]</value>
      <webElementGuid>8dfff42d-8b1e-4469-981a-d3d07fbe640b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div/h3/div/div/span[2]</value>
      <webElementGuid>9fddd768-1195-4306-bfe7-e70abf0e483e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 issues)'])[1]/following::span[2]</value>
      <webElementGuid>0d216f61-15da-4689-816e-ca7734dc7d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Issue'])[1]/preceding::span[1]</value>
      <webElementGuid>e02d350e-a666-429f-80fc-5f0c6e392f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new']/parent::*</value>
      <webElementGuid>fd03c667-f3c9-4578-b344-9dc4aa67e38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/div/span[2]</value>
      <webElementGuid>e63e9ac9-47ca-4184-bcbf-2bb642c49a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create new' or . = 'Create new')]</value>
      <webElementGuid>f3628795-cbea-42e9-a616-015d5488fa2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
