<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose Project</name>
   <tag></tag>
   <elementGuidId>c27d9757-3771-4e07-a7cf-144fb58fd27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dropdown_span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d75decb-e614-4b7c-9abf-9cf2b37669dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_span</value>
      <webElementGuid>f6c0b50b-ae2e-4bea-b939-b9ce94f0938c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose Project</value>
      <webElementGuid>465bb013-aade-4ac6-bdce-230400970085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;header main_header&quot;]/div[@class=&quot;topBar mainTopbar&quot;]/div[@class=&quot;topleft&quot;]/span[@class=&quot;ml-0 ml-lg-2 ml-md-3 dropdown_span_div&quot;]/span[@class=&quot;dropdown_span&quot;]</value>
      <webElementGuid>95e2463f-59b5-4601-b519-ad94c4a63e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/span[2]/span</value>
      <webElementGuid>4a6a2913-da40-4c8f-a511-438c759938f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[1]</value>
      <webElementGuid>f57151c3-4189-410e-9888-bc88b2502ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Choose Project']/parent::*</value>
      <webElementGuid>d10b7f12-0e55-4351-96c4-51e7b2e00f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>bb7f6e5b-4b64-4faf-a6b0-a32c542499ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Choose Project' or . = 'Choose Project')]</value>
      <webElementGuid>9619ee35-790c-41b5-9175-ae1a805e1775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
