<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SP</name>
   <tag></tag>
   <elementGuidId>576ba8ff-6b0a-4e6f-89fc-251eaace5521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div[2]/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.userProfileImg-span.userProfileImg.bg-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ccd2306-79cd-4314-8812-f40b9f210232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userProfileImg-span userProfileImg bg-secondary</value>
      <webElementGuid>58199ef5-b149-4a39-be81-55ba6aab0c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SP</value>
      <webElementGuid>8d18e488-f4a4-49de-af30-2a6e5a137d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main_wrapper&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mainSection&quot;]/div[@class=&quot;head_main&quot;]/div[@class=&quot;header_topbar ml-auto&quot;]/div[@class=&quot;topBar topBarpadd&quot;]/div[@class=&quot;topleft topFlex&quot;]/div[@class=&quot;user-icons&quot;]/span[@class=&quot;userProfileImg-span userProfileImg bg-secondary&quot;]</value>
      <webElementGuid>1022d85e-ebec-4560-8f1d-f53daee5548f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[2]/div/div/div/span</value>
      <webElementGuid>0e088f7f-05e7-43fa-9e7e-159a4cdf357c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[1]</value>
      <webElementGuid>46f9a399-26fb-49c8-885a-61a235654c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::span[2]</value>
      <webElementGuid>3353b474-4984-455c-a442-c62b2bb95c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite People'])[1]/preceding::span[3]</value>
      <webElementGuid>92145c03-6222-4d22-a784-8960a1af8b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Id'])[1]/preceding::span[3]</value>
      <webElementGuid>8213fb36-75cf-4d4f-afaf-a6be66d31a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SP']/parent::*</value>
      <webElementGuid>0db06b17-efed-4173-96a7-d1e1102651e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/span</value>
      <webElementGuid>6d69ba36-f4bb-471d-b9c3-346ff4381d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SP' or . = 'SP')]</value>
      <webElementGuid>989f913f-3c28-4b7b-96c7-112354b37855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
