<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Your Team</name>
   <tag></tag>
   <elementGuidId>7803e46e-48b4-466c-9f69-0c29d0075359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yourTeam > span.dropdown_span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='yourTeam']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3520a324-09c2-4151-b806-edd98adbffd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_span</value>
      <webElementGuid>523a299b-68d6-4331-84ad-bf15eaaf082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Team</value>
      <webElementGuid>ce3e22a7-2528-46f4-994f-9d7bfe62c1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yourTeam&quot;)/span[@class=&quot;dropdown_span&quot;]</value>
      <webElementGuid>10fff38b-0a99-400e-8c58-7998c45b7030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='yourTeam']/span</value>
      <webElementGuid>5899d7cf-6454-49f4-84fa-67a77d5b7a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Katalon'])[1]/following::span[2]</value>
      <webElementGuid>8d887cd3-8a55-445a-8f47-f7c86648a259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[1]</value>
      <webElementGuid>cffcca90-e7e8-4680-a0ee-d7182e123850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Team']/parent::*</value>
      <webElementGuid>a2882f26-7ffa-4528-976b-696eac559074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>acd10562-c0c9-4f7c-8354-b045f7e1fc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Your Team' or . = 'Your Team')]</value>
      <webElementGuid>14a6c78e-7071-41a4-b973-d054a0d083e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
