<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobileno</name>
   <tag></tag>
   <elementGuidId>b37fee5d-0a52-4c86-9616-75bedc53455d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8240a0a-1bd7-47be-a5b6-02cb6eef10e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c991084f-b2fb-4bd0-ba63-d5399c01441a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72954805-4f77-4cd1-aa16-fffa8476cc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile No.</value>
      <webElementGuid>951b9daf-545e-4617-b723-2220696d4e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>4c78661d-e681-4cc7-b691-71b4efeb0501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid bg-white SignUpModule&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-5 col-md-7 signUpform&quot;]/div[@class=&quot;card card-plain&quot;]/form[1]/div[@class=&quot;card-body&quot;]/div[@class=&quot;input-group input-group-outline mb-3&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>ac3a5306-0304-46c9-af9e-9c64224e177a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>e42b3ce9-fd8d-4211-ab8a-b21a26f56a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div/div[4]/input</value>
      <webElementGuid>ec75da79-4e0d-4ef0-8fcc-c516f6db8790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>bac2383d-aa16-446b-9580-5893f57706e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Mobile No.']</value>
      <webElementGuid>dd0ca8b5-10b5-4274-ba74-a7a3d3df4a74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
